language: julia

notifications:
  email: false

os:
  - linux

julia:
  - 1.5
  - 1.6

branches:
  only:
    - master
    - /^release-.*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

codecov: true
coveralls: true

stages:
  - name: test
  - name: docs

jobs:
  include:
    - stage: Documentation
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(url="https://github.com/gkappler/LazyStrings.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.add("Documenter");'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: test
      os: linux
      script:
        - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(url="https://github.com/gkappler/LazyStrings.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
      after_success: |
        julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
