language: julia
notifications:
  email: false
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - 1.4
  - nightly
before_script:
  - git config --global user.name Tester
  - git config --global user.email mail@g-kappler.de
script: travis_wait julia --project -e 'using Pkg; Pkg.test(coverage=true)'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - arch: x86
      julia: 1.3
    - stage: Documentation
      julia: 1.3
      os: linux
      script:
        - git config --global user.name "Gregor Kappler"
        - git config --global user.email email
        - git config --global github.user gkappler
        - |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
            '
      after_success: skip
after_success: |
  julia -e '
    using Pkg
    Pkg.add("Coverage")
    using Coverage
    Codecov.submit(process_folder())'
